openapi: 3.1.0
info:
  title: MCP Edge
  version: 0.1.0
paths:
  /v1/sync:
    post:
      summary: Sync visit data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../shared/visit.schema.json"
      responses:
        "200":
          description: OK
