name = "mcp-worker"
main = "src/index.ts"
compatibility_date = "2025-06-01"
[vars]
EDGE_HMAC_KEY = "${EDGE_HMAC_KEY}"
[[kv_namespaces]]
binding = "APP_KV"
# Replace the following with your actual KV namespace ID
id = "<YOUR_KV_NAMESPACE_ID>"
# For preview (dev) environment, you can reuse the same namespace or specify another ID
preview_id = "<YOUR_KV_NAMESPACE_ID>"
