name: iOS CI
on: 
  push:
    paths:
      - 'ios-client/**'
  pull_request:
    paths:
      - 'ios-client/**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Build iOS Client
        run: |
          cd ios-client
          swift build
      
      - name: Run Tests
        run: |
          cd ios-client
          swift test
      
      - name: Archive for TestFlight
        if: github.ref == 'refs/heads/main'
        run: |
          cd ios-client
          # Note: This would require proper signing certificates and provisioning profiles
          # For now, just verify the project can be built
          echo "Archive step would upload to TestFlight here"